### ISSUE TITLE
Find a bug

### ISSUE THREAD

**Issue by CodiexCrypto** [r1ghtl3ft/Pancakeswap-Sniper-Bot-BSC#9]
When I opening help-button, the window doesn't works correctly. Please, fix it.

**Comment by r1ghtl3ft** [comment]
**Hello, CodiexCrypto.**
Thank you for feedback! I will fix it as soon as I can. If you find more bugs(or critical), I can give you cryptoreward.

**Comment by CodiexCrypto** [comment]
Thanks! I hope your program works with no bugs, because they are very cool :)
